services:
  app:
    build:
      context: .
    container_name: classreg_app
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__From=${SMTP_FROM}
      - Smtp__defaultCredentials=${SMTP_DEFAULTCREDENTIALS}
      - AdSettings__LdapPath=${LDAP_PATH}
      - Survey__InviteUrl=${SURVEY_INVITE_URL}
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
